# Generated by Django 4.2.2 on 2023-06-29 17:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user_addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddresses',
            old_name='address',
            new_name='receiver_address',
        ),
        migrations.RenameField(
            model_name='useraddresses',
            old_name='city',
            new_name='receiver_city',
        ),
        migrations.RenameField(
            model_name='useraddresses',
            old_name='postal_code',
            new_name='receiver_postal_code',
        ),
        migrations.RenameField(
            model_name='useraddresses',
            old_name='province',
            new_name='receiver_province',
        ),
    ]
