# Generated by Django 4.2.2 on 2023-06-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_addresses', '0002_rename_address_useraddresses_receiver_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddresses',
            name='receiver_family',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='useraddresses',
            name='receiver_name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='useraddresses',
            name='receiver_phone',
            field=models.CharField(max_length=11),
        ),
    ]
