# Generated by Django 4.2.2 on 2023-07-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_addresses', '0003_alter_useraddresses_receiver_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddresses',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
