# Generated by Django 4.2.3 on 2023-07-09 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=6, null=True, unique=True)),
                ('payment_status', models.CharField(blank=True, choices=[('OPEN_ORDER', 'باز'), ('PENDING_PAYMENT', 'در انتظار پرداخت'), ('PAID', 'پرداخت شده')], max_length=20, null=True)),
                ('delivery_status', models.CharField(blank=True, choices=[('CANCELED', 'لغو شده'), ('PENDING', 'در انتظار تایید'), ('PROCESSING', 'درحال پردازش'), ('SHIPPED', 'ارسال شده'), ('DELIVERED', 'تحویل داده شده')], max_length=20, null=True)),
                ('repayment_date_expire', models.DateTimeField(blank=True, null=True)),
                ('lock_for_payment', models.BooleanField(default=False)),
                ('tracking_code', models.CharField(blank=True, max_length=155, null=True)),
                ('coupon_effect_price', models.PositiveIntegerField(default=0)),
                ('shipping_effect_price', models.IntegerField(default=0)),
                ('date_ordered', models.DateTimeField(blank=True, null=True)),
                ('date_shipped', models.DateTimeField(blank=True, null=True)),
                ('date_delivered', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_ordered'],
            },
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_phone', models.CharField(max_length=11)),
                ('receiver_city', models.CharField(max_length=100)),
                ('receiver_province', models.CharField(max_length=100)),
                ('receiver_postal_code', models.CharField(max_length=100)),
                ('receiver_address', models.CharField(max_length=300)),
                ('receiver_national_code', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('final_price', models.IntegerField(blank=True, editable=False, null=True)),
                ('final_price_before_discount', models.IntegerField(blank=True, editable=False, null=True)),
                ('final_discount', models.IntegerField(blank=True, editable=False, null=True)),
                ('final_profit', models.IntegerField(blank=True, editable=False, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order_management.order')),
            ],
        ),
    ]
