# Generated by Django 4.2.1 on 2023-06-11 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('product_management', '0005_alter_productvariant_options_productvariant_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coupon_management', '0001_initial'),
        ('shipping_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status',
                 models.CharField(choices=[('PAID', 'پرداخت شده'), ('NOT_PAID', 'پرداخت نشده')], default='پرداخت نشده',
                                  max_length=20)),
                ('status', models.CharField(blank=True,
                                            choices=[('CANCELED', 'لغو شده'), ('PENDING', 'در انتظار تایید'),
                                                     ('PROCESSING', 'درحال پردازش'), ('SHIPPED', 'ارسال شده'),
                                                     ('DELIVERED', 'تحویل داده شده')], max_length=20, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('tracking_code', models.CharField(blank=True, max_length=155, null=True)),
                ('coupon_effect_price', models.PositiveIntegerField(default=0)),
                ('shipping_effect_price', models.IntegerField(default=0)),
                ('date_ordered', models.DateTimeField(blank=True, null=True)),
                ('date_shipped', models.DateTimeField(blank=True, null=True)),
                ('date_delivered', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_ordered'],
            },
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_phone', models.CharField(max_length=11)),
                ('receiver_city', models.CharField(max_length=100)),
                ('receiver_province', models.CharField(max_length=100)),
                ('receiver_postal_code', models.CharField(max_length=100)),
                ('receiver_address', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('final_price', models.IntegerField(blank=True, editable=False, null=True)),
                ('final_price_before_discount', models.IntegerField(blank=True, editable=False, null=True)),
                ('final_discount', models.IntegerField(blank=True, editable=False, null=True)),
                ('final_profit', models.IntegerField(blank=True, editable=False, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items',
                                            to='order_management.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='baskets',
                                              to='product_management.product')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='baskets',
                                              to='product_management.productvariant')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='order_management.orderaddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='coupon_management.coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='orders', to='shipping_management.shippingrate'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
