# Generated by Django 4.2.1 on 2023-06-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order_management', '0002_remove_order_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderaddress',
            name='receiver_national_code',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
