# Generated by Django 4.2.2 on 2023-07-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order_management', '0003_orderaddress_receiver_national_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'پرداخت شده'), ('NOT_PAID', 'در انتظار پرداخت')],
                                   default='در انتظار پرداخت', max_length=20),
        ),
    ]
