# Generated by Django 4.2.2 on 2023-07-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order_management', '0004_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'پرداخت شده'), ('PENDING_PAYMENT', 'در انتظار پرداخت')],
                                   max_length=20),
        ),
    ]
