# Generated by Django 4.2.3 on 2023-07-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0004_alter_order_address_alter_order_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_delivery_status_updated',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
