# Generated by Django 4.2.3 on 2023-07-04 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('refund_management', '0005_remove_refundorderitem_order_item'),
        ('order_management', '0007_rename_status_order_delivery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='refund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='order_item', to='refund_management.refundorderitem'),
        ),
    ]
