# Generated by Django 4.2.3 on 2023-07-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order_management', '0008_orderitem_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderaddress',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
