# Generated by Django 4.2.3 on 2023-07-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0009_orderaddress_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
