# Generated by Django 4.2.3 on 2023-07-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0010_order_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='repayment_date_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
