# Generated by Django 4.2.3 on 2023-07-07 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('order_management', '0011_order_repayment_date_expire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='is_delete',
        ),
    ]
