# Generated by Django 4.2.3 on 2023-07-07 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_management', '0004_remove_coupon_is_active'),
        ('shipping_management', '0007_rename_is_delete_shippingservice_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order_management', '0012_remove_orderitem_is_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderaddress',
            name='is_delete',
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order_management.orderaddress'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='coupon_management.coupon'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shipping_management.shippingrate'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
