# Generated by Django 4.2.3 on 2023-07-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0013_remove_orderaddress_is_delete_alter_order_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lock_for_payment',
            field=models.BooleanField(default=False),
        ),
    ]
