# Generated by Django 4.2.1 on 2023-06-03 15:42

import django.db.models.deletion
import imagekit.models.fields
import mptt.fields
from django.db import migrations, models

import site_shop.category_management.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(
                    upload_to=site_shop.category_management.models.upload_category_path)),
                ('title_ir', models.CharField(db_index=True, max_length=100)),
                ('title_en', models.CharField(db_index=True, max_length=100)),
                ('display_title', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('order', models.IntegerField(blank=True, default=1, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent',
                 mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                            related_name='children', to='category_management.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='CategoryBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(
                    upload_to=site_shop.category_management.models.upload_category_path)),
                ('image_alt', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('order', models.IntegerField(blank=True, default=1, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners',
                                               to='category_management.category')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
