# Generated by Django 4.2.3 on 2023-07-09 16:08

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import site_shop.product_management.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(default='images/products/default_product.png', upload_to=site_shop.product_management.models.upload_product_path)),
                ('title_ir', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True, unique=True)),
                ('sku', models.IntegerField(blank=True, db_index=True, editable=False, null=True, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0)),
                ('special_price', models.PositiveIntegerField(blank=True, null=True)),
                ('special_price_start_date', models.DateTimeField(blank=True, null=True)),
                ('special_price_end_date', models.DateTimeField(blank=True, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('order', models.IntegerField(blank=True, default=1, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='ProductVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30, verbose_name='user ip')),
            ],
            options={
                'verbose_name': 'product visit',
                'verbose_name_plural': 'product visits',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserFavoriteProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VariantPrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VariantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ir', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100)),
                ('select_style', models.CharField(choices=[('RADIO_BOX', 'Radio Box'), ('RADIO_COLOR', 'Radio Color'), ('DROP_DOWN', 'Drop down menu')], default='RADIO_BOX', max_length=20)),
                ('is_none', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VariantValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('color_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Color (Not Required)')),
                ('prefix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.variantprefix')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.varianttype')),
            ],
        ),
        migrations.CreateModel(
            name='UserRecentVisitedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.product')),
            ],
        ),
    ]
