# Generated by Django 4.2.3 on 2023-07-09 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category_management', '0001_initial'),
        ('product_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecentvisitedproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userfavoriteproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.product'),
        ),
        migrations.AddField(
            model_name='userfavoriteproducts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productvisit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='product_management.product'),
        ),
        migrations.AddField(
            model_name='productvisit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product_management.product'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product_management.varianttype'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_management.variantvalue'),
        ),
        migrations.AddField(
            model_name='productproperty',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='product_management.product'),
        ),
        migrations.AddField(
            model_name='productproperty',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.property'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(db_index=True, related_name='products', to='category_management.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='product_management.varianttype'),
        ),
    ]
