# Generated by Django 4.2.1 on 2023-06-06 20:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0002_alter_productproperty_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='special_price_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='special_price_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
