# Generated by Django 4.2.3 on 2023-07-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product_management', '0006_product_is_delete_productproperty_is_delete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
