# Generated by Django 4.2.3 on 2023-07-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0007_alter_productvariant_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='productproperty',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='productvisit',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='variantprefix',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='varianttype',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='variantvalue',
            name='is_delete',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='varianttype',
            name='select_style',
            field=models.CharField(choices=[('RADIO_BOX', 'Radio Box'), ('RADIO_COLOR', 'Radio Color'), ('DROP_DOWN', 'Drop down menu')], default='RADIO_BOX', max_length=20),
        ),
    ]
