# Generated by Django 4.2.3 on 2023-07-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefundOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_REQUESTED', 'درخواست نشده'), ('PENDING', 'در انتظار تایید'), ('ACCEPTED', 'تایید شده'), ('REJECTED', 'درخواست رد شد')], default='درخواست نشده', max_length=20)),
                ('reject_message', models.TextField(blank=True, null=True)),
                ('refunded_price', models.TextField(blank=True, null=True)),
                ('date_requested', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
