# Generated by Django 4.2.1 on 2023-06-11 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_REQUESTED', 'درخواست نشدهق'), ('PENDING', 'در انتظار تایید'), ('ACCEPTED', 'تایید شده'), ('REJECTED', 'درخواست رد شد')], default='درخواست نشدهق', max_length=20)),
                ('reject_message', models.TextField(blank=True, null=True)),
                ('date_requested', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='refund', to='order_management.orderitem')),
            ],
        ),
    ]
