# Generated by Django 4.2.1 on 2023-06-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refund_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundorderitem',
            name='status',
            field=models.CharField(choices=[('NOT_REQUESTED', 'درخواست نشده'), ('PENDING', 'در انتظار تایید'), ('ACCEPTED', 'تایید شده'), ('REJECTED', 'درخواست رد شد')], default='درخواست نشده', max_length=20),
        ),
    ]
