# Generated by Django 4.2.2 on 2023-07-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('refund_management', '0002_alter_refundorderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundorderitem',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
