# Generated by Django 4.2.3 on 2023-07-04 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0007_rename_status_order_delivery_status_and_more'),
        ('refund_management', '0003_refundorderitem_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundorderitem',
            name='order_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='refund', to='order_management.orderitem'),
        ),
    ]
