# Generated by Django 4.2.3 on 2023-07-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refund_management', '0005_remove_refundorderitem_order_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refundorderitem',
            name='is_delete',
        ),
        migrations.AddField(
            model_name='refundorderitem',
            name='refunded_price',
            field=models.TextField(blank=True, null=True),
        ),
    ]
