# Generated by Django 4.2.3 on 2023-07-09 16:08

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import site_shop.shipping_management.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=site_shop.shipping_management.models.upload_shipping_method_image_path)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, choices=[('آذربایجان شرقی', 'آذربایجان شرقی'), ('آذربایجان غربی', 'آذربایجان غربی'), ('اردبیل', 'اردبیل'), ('اصفهان', 'اصفهان'), ('البرز', 'البرز'), ('ایلام', 'ایلام'), ('بوشهر', 'بوشهر'), ('تهران', 'تهران'), ('چهارمحال وبختیاری', 'چهارمحال وبختیاری'), ('خراسان جنوبی', 'خراسان جنوبی'), ('خراسان رضوی', 'خراسان رضوی'), ('خراسان شمالی', 'خراسان شمالی'), ('خوزستان', 'خوزستان'), ('زنجان', 'زنجان'), ('سمنان', 'سمنان'), ('سیستان وبلوچستان', 'سیستان وبلوچستان'), ('فارس', 'فارس'), ('قزوین', 'قزوین'), ('قم', 'قم'), ('کردستان', 'کردستان'), ('کرمان', 'کرمان'), ('کرمانشاه', 'کرمانشاه'), ('کهگیلویه وبویراحمد', 'کهگیلویه وبویراحمد'), ('گلستان', 'گلستان'), ('گیلان', 'گیلان'), ('لرستان', 'لرستان'), ('مازندران', 'مازندران'), ('مرکزی', 'مرکزی'), ('هرمزگان', 'هرمزگان'), ('همدان', 'همدان'), ('یزد', 'یزد')], max_length=20, null=True)),
                ('all_area', models.BooleanField(default=False)),
                ('pay_at_destination', models.BooleanField(default=False)),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('free_shipping_threshold', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('order', models.IntegerField(blank=True, default=1, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('shipping_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping_management.shippingservice')),
            ],
            options={
                'ordering': ('order',),
                'unique_together': {('shipping_service', 'all_area', 'is_active'), ('shipping_service', 'area', 'is_active')},
            },
        ),
    ]
