# Generated by Django 4.2.2 on 2023-07-03 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('shipping_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shippingrate',
            unique_together={('shipping_service', 'area', 'all_area')},
        ),
    ]
