# Generated by Django 4.2.2 on 2023-07-03 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_management', '0003_alter_shippingrate_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shippingrate',
            unique_together={('shipping_service', 'area'), ('shipping_service', 'all_area')},
        ),
    ]
