# Generated by Django 4.2.2 on 2023-07-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_management', '0005_alter_shippingrate_all_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingrate',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shippingservice',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
