# Generated by Django 4.2.3 on 2023-07-07 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_management', '0006_shippingrate_is_delete_shippingservice_is_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingservice',
            old_name='is_delete',
            new_name='is_active',
        ),
        migrations.AlterUniqueTogether(
            name='shippingrate',
            unique_together={('shipping_service', 'all_area', 'is_active'), ('shipping_service', 'area', 'is_active')},
        ),
        migrations.RemoveField(
            model_name='shippingrate',
            name='is_delete',
        ),
    ]
