# Generated by Django 4.2.3 on 2023-07-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_management', '0007_rename_is_delete_shippingservice_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingservice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
