# Generated by Django 4.2.3 on 2023-07-07 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_management', '0003_alter_coupon_date_expire_alter_coupon_date_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='is_active',
        ),
    ]
