# Generated by Django 4.2.3 on 2023-07-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transaction_management', '0003_transaction_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
