# Generated by Django 4.2.3 on 2023-07-07 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_management', '0008_transaction_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_active',
        ),
    ]
