# Generated by Django 4.2.2 on 2023-06-30 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_usersearchhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
