# Generated by Django 4.2.2 on 2023-06-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
