# Generated by Django 4.2.3 on 2023-07-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyNewsletterService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=355)),
                ('activate_link', models.CharField(max_length=255, unique=True)),
                ('date_expire', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VerifyOTPService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PHONE', 'تلفن'), ('EMAIL', 'ایمیل')], max_length=5)),
                ('usage', models.CharField(choices=[('AUTHENTICATE', 'احراز هویت'), ('RESET_PASSWORD', 'بازیابی کلمه عبور'), ('VERIFY', 'تایید')], default='AUTHENTICATE', max_length=14)),
                ('to', models.CharField(max_length=355)),
                ('code', models.CharField(max_length=5)),
                ('date_expire', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
