# Generated by Django 4.2.1 on 2023-06-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification_notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifyotpservice',
            name='type',
            field=models.CharField(choices=[('PHONE', 'تلفن'), ('EMAIL', 'ایمیل')], max_length=5),
        ),
        migrations.AlterField(
            model_name='verifyotpservice',
            name='usage',
            field=models.CharField(choices=[('AUTHENTICATE', 'احراز هویت'), ('RESET_PASSWORD', 'بازیابی کلمه عبور'), ('VERIFY', 'تایید')], default='AUTHENTICATE', max_length=14),
        ),
    ]
