# Generated by Django 4.2.1 on 2023-06-06 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('verification_notification', '0002_alter_verifyotpservice_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyNewsletterService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=355)),
                ('activate_link', models.CharField(max_length=255, unique=True)),
                ('date_expire', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='verifyotpservice',
            old_name='expire_date',
            new_name='date_expire',
        ),
        migrations.AddField(
            model_name='verifyotpservice',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verifyotpservice',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
