# Generated by Django 4.2.2 on 2023-07-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification_notification', '0004_verifyotpservice_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifynewsletterservice',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
