# Generated by Django 4.2.3 on 2023-07-09 16:08

from django.db import migrations, models
import imagekit.models.fields
import site_setting.website_banner.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('HOME_PAGE_SLIDER_BANNER', 'اسلایدر صفحه اصلی 1350x450'), ('HOME_PAGE_LARGE_BANNER', 'بنر بزرگ صفحه اصلی 1350x170')], max_length=40)),
                ('title', models.CharField(max_length=100)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=site_setting.website_banner.models.upload_banner_path)),
                ('resize_width', models.PositiveIntegerField(default=0)),
                ('resize_height', models.PositiveIntegerField(default=0)),
                ('image_alt', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, default=1, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
