# Generated by Django 4.2.1 on 2023-06-03 18:44

from django.db import migrations, models

import site_setting.website_banner.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('SLIDER', 'SLIDER'), ('BANNER', 'BANNER')], max_length=6)),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=site_setting.website_banner.models.upload_banner_path)),
                ('image_alt', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.IntegerField(blank=True, default=1, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ('order',),
            },
        ),
    ]
