# Generated by Django 4.2.1 on 2023-06-03 19:31

import imagekit.models.fields
from django.db import migrations

import site_setting.website_banner.models


class Migration(migrations.Migration):
    dependencies = [
        ('website_banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitebanner',
            options={'ordering': ('order',)},
        ),
        migrations.AlterField(
            model_name='sitebanner',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(
                upload_to=site_setting.website_banner.models.upload_banner_path),
        ),
    ]
