# Generated by Django 4.2.3 on 2023-07-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_banner', '0003_sitebanner_resize_height_sitebanner_resize_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebanner',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
