# Generated by Django 4.2.3 on 2023-07-07 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_banner', '0004_sitebanner_is_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitebanner',
            name='is_delete',
        ),
    ]
