# Generated by Django 4.2.3 on 2023-07-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_banner', '0005_remove_sitebanner_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebanner',
            name='position',
            field=models.CharField(choices=[('HOME_PAGE_SLIDER_BANNER', 'اسلایدر صفحه اصلی 1350x450'), ('HOME_PAGE_LARGE_BANNER', 'بنر بزرگ صفحه اصلی 1350x170')], max_length=40),
        ),
    ]
